Checkpoint 19; AddressBook Attributes
```
F

Failures:

  1) AddressBook attributes responds to entries
     Failure/Error: expect(book).to respond_to(:entries)
       expected #<AddressBook:0x007fd1bc14b2d0> to respond to :entries
     # ./spec/address_book_spec.rb:7:in `block (3 levels) in <top (required)>'

Finished in 0.0131 seconds (files took 0.10667 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/address_book_spec.rb:5 # AddressBook attributes responds to entries

.

Finished in 0.00195 seconds (files took 0.12455 seconds to load)
1 example, 0 failures

.FF

Failures:

  1) AddressBook attributes initializes entries as an array
     Failure/Error: expect(book.entries).to be_an(Array)
       expected nil to be a kind of Array
     # ./spec/address_book_spec.rb:12:in `block (3 levels) in <top (required)>'

  2) AddressBook attributes initializes entries as empty
     Failure/Error: expect(book.entries.size).to eq(0)

     NoMethodError:
       undefined method `size' for nil:NilClass
     # ./spec/address_book_spec.rb:17:in `block (3 levels) in <top (required)>'

Finished in 0.01647 seconds (files took 0.11971 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./spec/address_book_spec.rb:10 # AddressBook attributes initializes entries as an array
rspec ./spec/address_book_spec.rb:15 # AddressBook attributes initializes entries as empty

...

Finished in 0.00248 seconds (files took 0.11406 seconds to load)
3 examples, 0 failures

...FF

Failures:

  1) AddressBook#add_entry adds only one entry to the address book
     Failure/Error: book.add_entry('Ada Lovelace', '010.012.1815', 'augusta.king@lovelace.com')

     NoMethodError:
       undefined method `add_entry' for #<AddressBook:0x007fac22824378 @entries=[]>
     # ./spec/address_book_spec.rb:24:in `block (3 levels) in <top (required)>'

  2) AddressBook#add_entry adds the correct information to entries
     Failure/Error: book.add_entry('Ada Lovelace', '010.012.1815', 'augusta.king@lovelace.com')

     NoMethodError:
       undefined method `add_entry' for #<AddressBook:0x007fac22809d98 @entries=[]>
     # ./spec/address_book_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 0.00267 seconds (files took 0.11738 seconds to load)
5 examples, 2 failures

Failed examples:

rspec ./spec/address_book_spec.rb:22 # AddressBook#add_entry adds only one entry to the address book
rspec ./spec/address_book_spec.rb:29 # AddressBook#add_entry adds the correct information to entries

.....

Finished in 0.00351 seconds (files took 0.1078 seconds to load)
5 examples, 0 failures


```